apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi  # حجم التخزين الذي تحتاجه
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # بعد حذف البود، البيانات تظل محفوظة
  storageClassName: hostpath  # تأكد من أن هذه القيمة هي نفسها في StorageClass
  hostPath:
    path: /tmp/mysql-data  # المسار المحلي للتخزين (تأكد أنه موجود على جهازك)
